### ISSUE TITLE
Implement visit tracking for articles

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#2182]
* [x] Implement visit tracking for articles
* [x] Add support for menu item badge
* [x] Add a global option to disable visit tracking for articles

See https://community.woltlab.com/thread/257217-anzeige-neuer-artikel-in-der-hauptmen%C3%BCleiste/
