### ISSUE TITLE
Better tracking of new/changed phrases

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#2221]
* [x] Introduce two new fields in `wcfN_language_item`
  * [x] `languageCustomItemDisableTime` to track the time when a custom phrase has been disabled
  * [x] `languageItemOldValue` previous original value was for comparison, easier adjustment of custom phrases
* [x] Alter the phrase update mechanism to flag disable custom values
* [x] Add a comparison to the phrase edit window
* [x] Show a notice for recently disabled phrases on the package list
* [x] Filter by recently disabled phrases due to changes to the source values
* [x] Cleanup old values once the customized phrase has been re-enabled

See https://community.woltlab.com/thread/242007-tracking-new-phrases/
