### ISSUE TITLE
Implement a simple tracking system for arbitrary changes

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#2240]
The currently available history system is great for dealing with simple content, that consists of a simple message field (such as forum posts). This simplification comes at a price, as it does not allow tracking of multiple fields per object and cannot be handled through an abstract database table.

The solution is a central handler that provides a change tracking using a list of tracked fields that are saved in a dedicated database table per object. The data will be stored as a serialized array in a blob column, as this allows us for a maximum of flexibility and the contents does not require to be searchable at all. Using dedicated database tables also enables automatic cleanup using the original table's primary key as a foreign key.

* [x] Add `wcf\system\version\VersionTracker` to provide a generic API
* [x] Introduce the `com.woltlab.wcf.versionTracker.objectType` object type definition to register components
  * [x] Automatically creates the database table `<objectTable>_version` using the columns `objectID INT(10) NOT NULL` (foreign key!) and `data LONGBLOB`
* [x] Add `wcf\data\IVersionTrackerObject` providing the `getObjectID()` method
* [x] Populate stored data via `wcf\system\version\IVersionTrackerProvider::getTrackedData()`
  * [x] Add an abstract implementation that exposes the tracked fields via `public static string[] $trackedObjects`
* [x] Include tracking fields in the version table to expose the user and time of a change
* [x] Implement an abstract diff page that takes in an object type and id for comparison
* [x] Add "revert to version" support

**Comment by TimWolla** [comment]
> data LONGBLOB

Is there a specific reason you opted for LONGBLOB instead of a MEDIUMBLOB?

**Comment by dtdesign** [comment]
Text columns are usually defined as `MEDIUMTEXT`, for instance copying the contents of a `wcfN_article_content`-row will at worst occupy more than a `MEDIUMBLOB`.

**Comment by azerusDE** [comment]
<img width="352" alt="bildschirmfoto 2018-01-20 um 10 54 05" src="https://user-images.githubusercontent.com/1836347/35182200-42369ecc-fdd0-11e7-9ae1-c98832525190.png">
--
Unfortunately, I can not find an explanation for this function in your docs?

**Comment by dtdesign** [comment]
The migration docs focus around changes that are relevant for plugins that existed before. The version tracker is a separate feature that has been added in 3.1 and will be addressed separately - it has little to nothing to do with a migration.

**Comment by azerusDE** [comment]
Migration... new feature...i should have known better, sorry.
Would be glad if you explain the function with an example, if you have time for that. :-)
