### ISSUE TITLE
Migration docs for 3.0 -> 3.1

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#2517]
### [PHP API](https://docs.woltlab.com/migration_wsc-30_php.html)
* [x] Comments Overhaul #2222, #2223, #2231, #2219 
* [x] Optional `htmlContent` for activity events #2234 
* [x] Permission for viewing likes #2300 
* [x] Updating PIPs for DevTools #2331 
* [x] PIP for media providers #2356 
* [x] Re-process HTML messages #2438 

### [JavaScript](https://docs.woltlab.com/migration_wsc-30_javascript.html)
* [x] Accelerated Guest View / Tiny Builds #2277
* [x] Real error message in AJAX requests #2299
* [x] Consistent UX of forms in dialogs #2480
* [x] Helper functions for inline error messages c9e9e448

### [Templates](https://docs.woltlab.com/migration_wsc-30_templates.html)
* [x] Comments Overhaul #2222, #2223, #2231, #2219 
* [x] Redesigned ACP user list #2347 
* [x] Custom sidebar buttons on mobile #2494

### [CSS](https://docs.woltlab.com/migration_wsc-30_css.html)
* [x] New style variables #2314, #2317 
* [x] Use variables in `alert.scss` #2403 

### [Package Components](https://docs.woltlab.com/migration_wsc-30_package.html)
* [x] Cronjobs calculation switched to local time #2164 
* [x] Block pages from becoming the landing page #2344 
* [x] PIP for media providers #2356 
* [x] Limited forward-compatibility for plugins #2427
