### ISSUE TITLE
Update checklist 3.0 -> 3.1

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#2542]
* [x] Re-deploy all files and (acp-)templates.
* [x] Import all phrases.
* [x] Force-update the `page.xml` to set proper defaults due to the page-PIP bug that was fixed in RC 4.
* [x] Double-check the 3.0 -> 3.1 instruction blocks for any changes (including but not limited to any SQL changes).
