### ISSUE TITLE
Upgrade 5.2

### ISSUE THREAD

**Issue by BurntimeX** [WoltLab/WCF#2806]
- [x] Update `<hasFixedParent>`-tags (page.xml) see #2805 
- [x] Execute [update-com.woltlab.wcf_3.2_reactionUpdate.php](https://github.com/WoltLab/WCF/blob/next/wcfsetup/install/files/acp/update-com.woltlab.wcf_3.2_reactionUpdate.php)
- [x] Delete all dislikes if any exist.
