### ISSUE TITLE
Quality of Life Improvements for Developers

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#2819]
All changes below must only be active if **both** the debug mode and the developer tools are enabled.

* [x] Add a language toggle to the ACP's top menu, immediately changes the language of the active user.
* [x] Add a language toggle to the frontend, immediately changes the language of the active user. (May-be in `.pageNavigationIcons` or `.userPanelItems`?)
* [x] Disable the ACP session expiration.
* [x] **DebugPreparedStatement**
Enabling the debug mode should cause `WCF::getDB()->prepareStatement()` to return `DebugPreparedStatement` (deriving from `PreparedStatement)` which will raise an exception whenever the callee attempts to `fetch*()` any data without calling `execute()` at least once.

Anything else that should be changed? Add it to the list or leave a comment.
