### ISSUE TITLE
More resilent upgrade process

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#2847]
The upgrade process can fail far too easily and not only give little information regarding to where it fails, it also stops at simple things like existing tables. There are a few things that can and should be improved to decrease the likelihood of failures during an upgrade:

* [x] **Recursively validate if all relevant files are writable.** (#3042)
Directories with known large amounts of unrelated files, e. g. uploaded images, should be excluded. This applies to the Core only, which is by far the most sensitive part of the upgrade process.
* [x] **Create a dedicated log file, e. g. `log/YYYY-MM-DD-update-TIMESTAMP.txt`.** (#3043)
`TIMESTAMP` equals the start of the update, any step that is _to be_ performed is dumped to this log. This should make it a bit easier to backtrack the source of an issue, or at the very least give an idea of what has failed. It should include selected meta data, such as the package that is currently being processed.
* [x] **PHP based SQL PIP that manages database upgrades.** (#3065)
The SQL PIP lacks a lot of flexibility, fails too easily and in particular cannot deal with unexpected situations, examples include already existing tables or keys. Ideally, it should be possible to specify which state a database table should have and the API figures out what _actually_ needs to be done.
Bonus points for being able to allow customers with large sites to make certain database modifications, e. g. adding columns or indices, ahead of time before running the upgrade.
