### ISSUE TITLE
Consistent and simplier template scripting, reduce redundancy

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#2978]
Template scripting is a powerful feature, but it can quickly become confusing and outright unmaintainable when used too much, most of the time it could be easily simplified in the PHP code. **This is especially true for phrases which suffer from long lines and missing syntax highlighting.**

* [x] **Avoid deep and/or repetitive arrow chains.** (Replaced by #3190)
  Notifications are a perfect example for this, the common pattern makes use of repeated `$event->getAuthor()` calls rather than consistently assigning the variable `$author` with the same value.
* [x] **Use `getLink()` whenever available.** (Replaced by #3295)
  Quite a lot of times `{link}` is used, even in situations where there is a proper `wcf\data\ILinkableObject` that already exposes an identical `getLink()` method.
  * [x] **Always** set `forceFrontend` to force consistent links regardless of the environment.
    _The only exception are objects that are available in the admin panel only._
* [x] **Implement `IRouteController` for all DBOs that support it.**
  Eases the use of `getLink()` above.
* [ ] ~**More magic variables with guaranteed values.**~
  The variables may map to special objects that wrap around existing data structures. In case of the avatar, it needs to be guaranteed that changes to the session, e. g. `changeUser()`, do not cause outdated data.
  Examples include:
  * `$__user` instead of `$__wcf->getUser()`.
  * `$__avatar` instead of `$__wcf->getUserProfileHandler()->getAvatar()`.
* [x] **Generic templates**
  * [x] The label selection in sidebar templates was duplicated way too often. (see #3301)
