### ISSUE TITLE
Reduced complexity of phrases used in notifications

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#3190]
The notifications are overly complex due to the extensive use of template scripting, including access of nested objects, making it somewhat difficult to maintain and translate those phrases.

There are a few key principles that we need to apply to improve the situation:
* [x] Notifications should be clickable in the notification list, similar to how it behaves in the user panel menu.
* [x] Convert anchors into plain text `{$item}` instead of `<a href="{$linkToItem}">{$item}</a>`.
  _The anchors aren't clickable in the overlay anyway and they provide little to no value._
* [x] Reduce code complexity by passing references to inner objects rather than accessing them dynamically.
* [x] Avoid manual link creation and make use of `getLink()` (replaced by #3295) instead, `getTitle()` is another good candidate.
* [x] ~Figure out if we can reduce the code complexity by providing a shortcut for complex constructs for plurals.~ Replaced by #3191
* [x] Find out if we're able to merge phrases for the display in the software as well as in emails, thus greatly reducing the redundancy. (moved to #2492)
* [x] Shorten reaction-related template code (in language items) (see #3320)
