### ISSUE TITLE
Improve the mobile UI/UX

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#3953]
The mobile UI shows its age and the user requirements are constantly shifting. We should review certain aspects of the UI and find new approaches or adjust the existing ones:
* [x] Show a search button in the header similar to the one in the admin panel. -- #4608
* [x] Easier access to notifications. -- #4608
  * [x] ~Include a dedicated button in the header.~
  * [x] OR: Modify the user menu to use a tab navigation with icons. -- #4608
    The tabs could show "Notifications", "Conversations", "Moderation" and the "Control Panel" in this order with notifications shown first. The advantage of this approach would be a quicker access without an additional menu button while still having notifications accessible with a single tap.
* [x] ~Show the full breadcrumbs or find any other way to better indicate the current location. The forum is the worst offender with nested forums often carrying the same name, causing users to take a guess in what section a thread really is.~
* [x] Move important features such as the subscription out of the navigation items. Can we possibly move some of them into the `contentNavigation` area? -- #4315
* [x] The `contentNavigation` buttons should not span the full width, the age of tiny smartphones is coming to an end and it becomes more and more reasonable to put two buttons into one line. -- 08887c63
  * [x] ~Maybe experiment with some icon based buttons? The primary button could be shown in full while all others just use the icon? How do we solve the accessibility issue with the icons not necessarily being clear to the user?~

**Comment by TimWolla** [comment]
Related: #3282

**Comment by dtdesign** [comment]
This is partially implemented in https://github.com/WoltLab/WCF/tree/mobile-ui-page-header, however, the rabid hole has proven to be much deeper than anticipated. In order to prevent this from blocking the 5.4 release, the implementation is delayed until 5.5

**Comment by mutec** [comment]
Is it wanted that about 50% of the acp menu items are hidden for mobile devices or is this a bug within the current code?
The whole third level of menu items like "add xy" is missing at the moment.

![Screenshot_20220111_152128_com android chrome](https://user-images.githubusercontent.com/1749344/148960265-fb689dbc-92dd-44fc-b211-7ffedc7d9af1.jpg)

**Comment by dtdesign** [comment]
@mutec Thanks, I've totally overlooked those, these links have been added. However, I did chose to represent them as text links instead for consistency and better UX. The "plus" icon can be considered to be quite understandable, but other icons might not and there are no tooltips on touch interfaces.
