### ISSUE TITLE
META: Implement lazy loading for images whenever it makes sense

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#3980]
**This is a meta issue and affects other repositories too.**

* [ ] Implement lazy loading via the `loading="lazy"` attribute for `<img>`.
* [ ] Set `loading="eager"` to hint images that are known to be required to be loaded immediately.
* [ ] Be careful not to break backwards compatibility for code that relies on images being loaded right away. When in doubt, do not making any change.
* [ ] Check other repositories for images that are affected too.

See https://community.woltlab.com/thread/281830-native-lazy-loading/

**Comment by TimWolla** [comment]
Smileys have an explicit size now (#4145). I'm not sure however if they should be loaded lazily, because they are an important part of the user generated content and tend to be fairly small.

Opinions?

/cc @SoftCreatR

**Comment by SoftCreatR** [comment]
> tend to be fairly small

While this should be the case, I personally know a lot of forums, which are using animated gifs as smileys, some of them are 64px or bigger.

However, besides the fact, that PHP and/or HTML aren't the optimal ways to implement Lazy Loading, I personally would lazily load everything (at least everything outside the viewpoint).

Google also suggests lazily loading every image (except for the page logo and other images visible within the initial viewpoint), when possible. In our own implementation (via PHP only), every image receives `loading="lazy"`, except for the logo images and the first image or iframe that is found in the DOM.

**Comment by TimWolla** [comment]
> which are using animated gifs as smileys, some of them are 64px or bigger.

To clarify: "Small" was referring to the file size. While animated GIFs are somewhat larger, they still should be smallish even with large dimensions.

> I personally would lazily load everything (at least everything outside the viewpoint).

This viewport analysis is next to impossible to achieve.

I'm specifically wondering about smileys, because I really want to avoid images (smileys) popping up inline within a paragraph the user is currently reading just because the load was delayed for whatever reason (e.g. being within a railway tunnel while scrolling down). If it looks good for the search engine on paper, but feels bad for the user then it should be avoided.

Avatars are not important for the contents and media items / attachments are already mostly cleanly separated from the text content (usually being within their own paragraph), reducing this issue.

To be clear, I am not planning to set loading="eager" on smileys either. I'd leave the decision up the the browser like it already is.

**Comment by SoftCreatR** [comment]
> This viewport analysis is next to impossible to achieve.

Depends. If you are using JS based lazy loading (e.g. via intersection observer) only, this is doable. But as written before, when doing it via PHP/HTML by just setting the loading attribute to image and iframe elements, it's nearly impossible, yes.

> I really want to avoid images (smileys) popping up inline within a paragraph the user is currently reading just because the load was delayed for whatever reason (e.g. being within a railway tunnel while scrolling down). If it looks good for the search engine on paper, but feels bad for the user then it should be avoided.

Depends. If you are talking about layout shifting: Since dimensions are known (now), there won't be any layout shifting, because the space for the given dimensions will be preserved, until the image has been loaded. So yes, it's possible that images (smileys) pop up delayed, but without any visible change of the layout, so it won't disrupt the reader.

Either way, from what I can remember, layout shifting shouldn't happen, even if the dimensions are unknown, because when using native lazy loading, the first few bytes of every image are loaded anyways, to obtain basic image information (like dimensions). But providing proper dimensions for every image is best practice.

> I'd leave the decision up the the browser like it already is

By omitting the lazy attribute, I guess? Alternatively, you could set loading="auto" instead, which is the same as not including the attribute. But who knows, how other browsers will treat it in the future.

**Comment by cadeyrn** [comment]
> but without any visible change of the layout, so it won't disrupt the reader.

A layout shift is not the only way to disrupt the user. Smileys are an important part of the content (they have a meaning and can change how you have to interpret the textual content) and as such should not be delayed. That would be an annoying user experience, especially for users without a fast internet connection.

**Comment by SoftCreatR** [comment]
> > but without any visible change of the layout, so it won't disrupt the reader.
> 
> A layout shift is not the only way to disrupt the user. Smileys are an important part of the content (they have a meaning and can change how you have to interpret the textual content) and as such should not be delayed. That would be an annoying user experience, especially for users without a fast internet connection.

That's absolutely correct. However, this is also a problem without lazy loading, therefore not really an argument against it.

**Comment by cadeyrn** [comment]
I disagree. Lazy loading delays the loading of the images until they're in the viewport so it's clearly not the same.

**Comment by SoftCreatR** [comment]
I didn't say or mean, that the behavior is the same with or without lazy loading. However, if you see a problem here, then simply don't lazy load smileys or set loading="eager" (which is undesired as per [this](https://github.com/WoltLab/WCF/issues/3980#issuecomment-827382892) comment).

**Comment by dtdesign** [comment]
I agree with @cadeyrn here, smileys are an important bit in messages, because they _can_ carry information. I would set them to `loading="eager"` to force the browser to load them immediately. Since this is an explicitly requested behavior, I do not expect Lighthouse and others to complain, similar to things like event listeners bound to the global `scroll` event with `{passive: false}`.

**Comment by SoftCreatR** [comment]
That's absolutely fine, as long as you don't let the browser decide (via `loading="auto"` or omitting the attribute completely).

**Comment by TimWolla** [comment]
> I would set them to `loading="eager"` to force the browser to load them immediately.

4c39f0a86150bb2d3ddee72fb5bf395d7bafd463

**Comment by TimWolla** [comment]
Okay, with WoltLab Suite 5.4 we lazily load Avatars (except the inlined default avatar), Attachments, Media Files. We eagerly load smileys. Thus the bulk of the images with known dimensions now has a `loading` attribute.

I'm closing this issue at this point, because there's no more low-hanging fruit. Additional images will be adjusted based on the real-world experience.

@cadeyrn @SoftCreatR Thanks for your input!

**Comment by SoftCreatR** [comment]
You may be already aware of it, but if not, this is for you: Lazily loaded images won't be printed. They just don't appear on the print page. That's a downside of all the fancy lazy loading stuff.

**Comment by cadeyrn** [comment]
> Lazily loaded images won't be printed. They just don't appear on the print page

It depends on the browser. For Chrome you're right. There is an open issue to support printing lazy loaded images (https://bugs.chromium.org/p/chromium/issues/detail?id=875403) but it's still not implemented. Firefox supports this and is able to print the lazy loaded images.

**Comment by dtdesign** [comment]
This is an acceptable trade-off, I strongly consider this to be a bug and I expect Chrome/Safari to resolve this issue at some point - and we all know who will fix it first. The benefits of lazy loading, especially on mobile devices or generally slow connection, outweighs the crippled printing experience.
